# Generated by Django 5.1.6 on 2025-02-27 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 27, 10, 54, 41, 724730, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
