# Generated by Django 5.1.6 on 2025-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='test_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
    ]
