# Generated by Django 5.1.6 on 2025-02-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appuser_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='test_type',
        ),
    ]
