# Generated by Django 4.2.20 on 2025-04-03 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 3, 17, 34, 19, 644027, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
